# Generated by Django 4.0.5 on 2024-08-09 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_weekly', models.BooleanField(default=False)),
                ('schedule_time', models.DateTimeField()),
                ('last_run_timestamp', models.DateTimeField(blank=True, null=True)),
                ('next_run_timestamp', models.DateTimeField(blank=True, null=True)),
                ('job_parameters', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
