# Generated by Django 4.0.5 on 2024-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user'], name='jobs_job_user_id_d7ccac_idx'),
        ),
    ]
