# Generated by Django 4.0.5 on 2024-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_jobs_job_user_id_d7ccac_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='after_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
