# Generated by Django 4.0.5 on 2024-08-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_after_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='after_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
